language: node_js
env:
  global:
    - GH_REF: github.com/w3c/coga.git
    - secure: "Ri4W7NtsAaytbK2rXHP8idkVDHQZtNCR5RvH0XDuq1cVqAj/QPBr4etF3bDgVrY+nq/83IEgOMhHb3q/TGHOh3Ootzin+wQt0ZGHgEvmAf8tTPKNnUg7VQ0DrMQoll3ijPiAWBajEe7LFwMBecJg+W7bd1w911l0SnKbhlbkRL0="
    
git:
  depth: 3
  
branches:
  only:
    master

before_script:
  - git config --global user.email "cooper@w3.org"
  - git config --global user.name "michael-n-cooper"
  
script:
  - cd ../..
  - mkdir gh-pages
  - cd gh-pages
  - git clone --depth=1 --branch=gh-pages https://github.com/w3c/coga.git
  - cd coga
  - curl https://labs.w3.org/spec-generator/?type=respec"&"url=https://rawgit.com/w3c/coga/master/user-research/index.html -o user-research/index.html -f
  - curl https://labs.w3.org/spec-generator/?type=respec"&"url=https://rawgit.com/w3c/coga/master/issue-papers/index.html -o issue-papers/index.html -f
  - curl https://labs.w3.org/spec-generator/?type=respec"&"url=https://rawgit.com/w3c/coga/master/gap-analysis/index.html -o gap-analysis/index.html -f
  - curl https://labs.w3.org/spec-generator/?type=respec"&"url=https://rawgit.com/w3c/coga/master/extension/index.html -o extension/index.html -f
  - curl https://labs.w3.org/spec-generator/?type=respec"&"url=https://rawgit.com/w3c/coga/master/techniques/index.html -o techniques/index.html -f

after_success:
  - git add .
  - git commit -m "Generated by TRAVIS-CI"
  - git push "https://${GH_TOKEN}@${GH_REF}" gh-pages
